export const MOON_XYZ = 'MOONHOLDINGS.XYZ'
export const MOON_HOLDINGS = 'Moon Holdings'
export const LOGIN = 'Login'
export const GET_STARTED = 'Get Started'
export const TITLE_HOME = 'Moon Holdings | Your Crypto Portfolio Tracker'
export const TITLE_SIGNUP = 'Moon Holdings Sign Up'
export const TITLE_PRIVACY_POLICY = 'Moon Holdings | Privacy Policy'
export const TITLE_TERMS_SERVICE = 'Moon Holdings | Terms Of Service'
